# Generated by Django 6.0.5 on 2026-05-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_carrito_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='es_repartidor',
            field=models.BooleanField(default=False),
        ),
    ]
